version: "3.8"
services:
  generic-video-site:
    container_name: generic-video-site
    image: nas3/generic-video-site:local
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - VIDEO_BASE_DIR=/app/data
      - DATABASE_URL=sqlite:///./db/user_preferences.db
      - OLLAMA_URL=http://ollama:11434
      - OLLAMA_MODEL=llama3.1:8b
    restart: unless-stopped
    volumes:
      - ./data:/app/data:ro
      - ./db:/app/db:rw
    # Run as root to avoid SQLite permission issues in deployment
    user: "0:0"
    # Health check
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama_models:/root/.ollama
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:11434/api/tags"]
      interval: 30s
      timeout: 10s
      retries: 5
    restart: unless-stopped

volumes:
  ollama_models:
